package no.idporten.eudiw.demo.verifier.openid4vp;

import com.nimbusds.jose.JWSAlgorithm;
import com.nimbusds.jose.JWSVerifier;
import com.nimbusds.jwt.SignedJWT;
import id.walt.sdjwt.SimpleJWTCryptoProvider;
import id.walt.sdjwt.VerificationResult;
import no.idporten.eudiw.demo.verifier.StatusCommunicationException;
import no.idporten.eudiw.demo.verifier.VerificationException;
import no.idporten.eudiw.demo.verifier.config.ConfigProvider;
import no.idporten.eudiw.demo.verifier.tsl.StatusSdJwt;
import no.idporten.eudiw.demo.verifier.tsl.TokenStatuslistService;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.junit.jupiter.MockitoExtension;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.net.URI;
import java.security.cert.X509Certificate;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

@DisplayName("When processing OpenID4VP responses")
@ExtendWith(MockitoExtension.class)
class OpenID4VPResponseServiceTest {

    private static final Logger log = LoggerFactory.getLogger(OpenID4VPResponseServiceTest.class);
    @Mock
    private VerificationTransactionService verificationTransactionService;

    @Mock
    private ConfigProvider configProvider;

    @InjectMocks
    private OpenID4VPResponseService openID4VPResponseService;

    @Mock
    private TokenStatuslistService tokenStatusListService;


    @DisplayName("with vp-token of type sd-jwt")
    @Nested
    class SDJwt {


        @DisplayName("from Hellas throws expected exception due to invalid signature because of expired certificate")
        @Test
        void retrieveClaimsFromSDJwtCredential_Hellas() {
            String vpToken = "eyJhbGciOiAiRVMyNTYiLCAidHlwIjogImRjK3NkLWp3dCIsICJ4NWMiOiBbIk1JSUNpakNDQWpDZ0F3SUJBZ0lVRmlNQ1dmcXBQRXJGMVdrNlhVRVdkWGxFc284d0NnWUlLb1pJemowRUF3SXdQVEVlTUJ3R0ExVUVBd3dWVUVsRUlFbHpjM1ZsY2lCRFFTQXRJRWRTSURBeE1RNHdEQVlEVlFRS0RBVkhVazVGVkRFTE1Ba0dBMVVFQmhNQ1IxSXdIaGNOTWpVeE1UQXpNVE16TVRVMFdoY05Nall4TWpBNE1UTXpNVFUwV2pCSE1TZ3dKZ1lEVlFRRERCOXpibVl0TnpRNE5qUXViMnN0YTI1dkxtZHlibVYwWTJ4dmRXUXVibVYwTVE0d0RBWURWUVFLREFWSFVrNUZWREVMTUFrR0ExVUVCaE1DUjFJd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFUbmVvSjZhdTl2dHRBRWtaVzhYWGlKOWxlM1Z3YkZaQU50Uk1nVUFoSEdUR3pFL3M0UldTWU5tNEVTZFhEQVYrS1hsb2FwL3l0N0dORGdSc3J6SWdYVm80SUJBakNCL3pBSkJnTlZIUk1FQWpBQU1CMEdBMVVkRGdRV0JCUTVUaDkvSTI5TzdGNmRGa3ppR3lWRnkvOEhRekI0QmdOVkhTTUVjVEJ2Z0JROWZWcTlaaWZCcmRJVjFnTDg5VU14RkMrSHk2RkJwRDh3UFRFZU1Cd0dBMVVFQXd3VlVFbEVJRWx6YzNWbGNpQkRRU0F0SUVkU0lEQXhNUTR3REFZRFZRUUtEQVZIVWs1RlZERUxNQWtHQTFVRUJoTUNSMUtDRkFSNHVJc1ZXUHIrdTRaK3VCQzZsblAzTGlLRU1CVUdBMVVkSlFFQi93UUxNQWtHQnlpQmpGMEZBUUl3TWdZRFZSMGZCQ3N3S1RBbm9DV2dJNFloYUhSMGNEb3ZMemd6TGpJeE1pNDNNaTR4TVRRNk9EQTRNaTlqY213dWNHVnRNQTRHQTFVZER3RUIvd1FFQXdJSGdEQUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpQWFsbnhVa25mWGd1N2JEbjVBQS9veWZCaGFNcGZwdmdlWkVnc002Q2hrSWdJaEFJSUdueVU4NTFSUVJxQ0trRC9Dc3RDY2dad1U4R0JDQ1plbzNSR2tySVNkIl19.eyJfc2QiOiBbIkFCbjhpV0xEMVdudnFoQk9KZTllVTNQMk92YXgwREJtWEJ2RmNWcDBpU3ciLCAiRDc3ZU45dWZoMFl4YjRaMEN1NFNuQ1kxdDBZN0RPSDd6QWhmUzcyVGhnVSIsICJJa2I4ZzBiX2VveFFfUXo4dEFNNExKZnhIb3JGMzlSejV2U1pBMmcxLU5ZIiwgIktGN2o0QS1ULWZuQlF6YlVvRWhjYUROM1J2Y050bUR1WU5yREQxdHpUVm8iLCAiWUUwaHBUc1JSRE5VQnZ0X01vakxmQ25MQU9Wbi1fWFpGRnRpYnpyeDJ5ayIsICJaWEszOGdpVHViaHhZOEFmMFd6aUtWc3lOUDB5TkJaT3FPQnk5WTJld0N3IiwgIl9pa0xfTU8xVkVJRUgwN3dxX3lZT3VmWTlPclRLWVdiTzR4QjhrSVlSVXMiLCAiYktESWF3SHBJeS0ySkhvejJ4bFZGRGVIOVkxOUVhRlFnQ1gxdW4tQ0VoYyIsICJsMldIcVBETk9QUjAyRUwyWFdFOFBlOU51YXdSTWcxMjgwbXNyMUJ3ZkU0Il0sICJpc3MiOiAiaHR0cHM6Ly9zbmYtNzQ4NjQub2sta25vLmdybmV0Y2xvdWQubmV0OjU2MDAiLCAiaWF0IjogMTc2NTQxMTIwMCwgImV4cCI6IDE3NzMxODcyMDAsICJ2Y3QiOiAidXJuOmV1ZGk6cGlkOjEiLCAiX3NkX2FsZyI6ICJzaGEtMjU2IiwgImNuZiI6IHsiandrIjogeyJrdHkiOiAiRUMiLCAiY3J2IjogIlAtMjU2IiwgIngiOiAiVk9rdEpoSnV3T0dWY1Npb25SZVZ5UjdUbC1Sa183aExuVWJNelBHd3BRVSIsICJ5IjogIlFNY0NqcHZkM2c0bVRnWWp4UTk2amxpekJGT2RKdElCV2FublVPckRJZ1kifX19.8Z-DemK0uUvpXgXiiIsQ3AU9rt2OYVFqEeYUPe2IY5iuNZUo_LSP65-gSwu2bDa-2Wa2PwT2kQAGu_wSCk1e8A~WyI0Vm00cnBSUnBnbURiajJ1SWhqV3NBIiwgImdpdmVuX25hbWUiLCAiTWFyaW9zIl0~WyJrNjVEUUFLSWJXN192R0wxUVBqMHdRIiwgImZhbWlseV9uYW1lIiwgIk1lbmV4ZXMiXQ~WyItbVRzWURfQU16R0hHYVBBQUxrVzdnIiwgImJpcnRoZGF0ZSIsICIyMDI1LTEyLTExIl0~WyJ5dy1ZMVlISjktREhHVGJVbmpRZS13IiwgIm5hdGlvbmFsaXRpZXMiLCBbeyIuLi4iOiAicE0tWGV3WHVXdm9LaUZhZG5TUTJwRTJ1OUF1cXE0ZDI4dG9HZWhpUjE4cyJ9XV0~WyJWM0dYdkx2SDJGdENpMkNzZzFwbWNRIiwgInBsYWNlX29mX2JpcnRoIiwgeyJfc2QiOiBbIlNoWUZuRTBYZUFtcGIxSnpMS3lIRHVMSXJfTXM2WnFxTENKcDBVNDlCenMiLCAiYkphaUROcTNTbEZjd1dabXpMTG9vdUw2OVRlaDlBYjN4VUtaVXJTdkdUayIsICJtd2ktNF9yWXYyeG9VRlhOVGt2WXIybExOajZMdEVNdWhPWVNNanBzc3RJIl19XQ~WyJ6VHVqWUFoSE5ibVk2X1lXSEoyV0JnIiwgImNvdW50cnkiLCAiR3JlZWNlIl0~WyJnNXVZRFJDblVfaWU3MzVEbk9aQ0d3IiwgInJlZ2lvbiIsICJBdHRpY2EiXQ~WyJGQlo3YnkxbW9nS1ktMFhSdk9RTHBRIiwgImxvY2FsaXR5IiwgIkF0aGVucyJd~eyJ0eXAiOiJrYitqd3QiLCJhbGciOiJFUzI1NiJ9.eyJzZF9oYXNoIjoiMmh5U1V5SU9hX2hhaFFHMUgyb2hEXy1LNVFqMU5Sb0dIb0ZRVHpNOV9zayIsImF1ZCI6Ing1MDlfc2FuX2RuczpkZW1vLWJydWtlcnN0ZWQudGVzdC5laWRhczJzYW5ka2Fzc2UubmV0Iiwibm9uY2UiOiJiNmM4NTk1Mi0wNDYwLTQzMWYtOWRhNS1lMzUxZjA4NGRkN2IiLCJpYXQiOjE3NjU0NTk4MDl9.8ZTzLWKCluaqv1VBUCISsje3i-cHgI37S31JbRPG3MnH_oFRmSanV5EJ6BlD9ZDka8lI2et2lcQkg4z2uQ9dZw";
            VerificationException e = assertThrows(VerificationException.class, () -> openID4VPResponseService.handleSDJwt(vpToken));
            assertNotNull(e.getMessage());
            assertTrue(e.getMessage().contains("Signature verified: false"), e.getMessage());
            assertTrue(e.getMessage().contains("disclosures verified: true"), e.getMessage());
        }

        // vp-token invalid?
        @DisplayName("from Italia throws expected exception due to Invalid selective disclosure")
        @Test
        void retrieveClaimsFromSDJwtCredential_Italia() {
            final String vpToken = "eyJhbGciOiAiRVMyNTYiLCAidHlwIjogImRjK3NkLWp3dCIsICJ4NWMiOiBbIk1JSUM0RENDQW9XZ0F3SUJBZ0lVVkRGWEV1eWMzRkI0RTdwY1NBbUpkckRxZFRZd0NnWUlLb1pJemowRUF3SXdYREVlTUJ3R0ExVUVBd3dWVUVsRUlFbHpjM1ZsY2lCRFFTQXRJRkJVSURBeU1TMHdLd1lEVlFRS0RDUkZWVVJKSUZkaGJHeGxkQ0JTWldabGNtVnVZMlVnU1cxd2JHVnRaVzUwWVhScGIyNHhDekFKQmdOVkJBWVRBbEJVTUI0WERUSTFNRFF4TURFME16WTFPVm9YRFRJMk1EY3dOREUwTXpZMU9Gb3dVakVVTUJJR0ExVUVBd3dMVUVsRUlFUlRJQzBnTURFeExUQXJCZ05WQkFvTUpFVlZSRWtnVjJGc2JHVjBJRkpsWm1WeVpXNWpaU0JKYlhCc1pXMWxiblJoZEdsdmJqRUxNQWtHQTFVRUJoTUNVRlF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVRJUXVZNUZ3MWxlYkZ3aEFYaXNJYm5tVDBIaG1aQzMwYVQzMUptWEFBaVVXZjNBckhrTG1wSlR4R0RVa0tvM2NydU5JdnhFYU5JTk02aDJYa1E0OHFwbzRJQkxUQ0NBU2t3SHdZRFZSMGpCQmd3Rm9BVS9GcTZ4Mk1oMEZUS1Q1UjVmZVdxMDhTK21KRXdHd1lEVlIwUkJCUXdFb0lRYVhOemRXVnlMbVYxWkdsM0xtUmxkakFXQmdOVkhTVUJBZjhFRERBS0JnZ3JnUUlDQUFBQkFqQkRCZ05WSFI4RVBEQTZNRGlnTnFBMGhqSm9kSFJ3Y3pvdkwzQnlaWEJ5YjJRdWNHdHBMbVYxWkdsM0xtUmxkaTlqY213dmNHbGtYME5CWDFCVVh6QXlMbU55YkRBZEJnTlZIUTRFRmdRVXBUV0ZmQVl1K1JSZkJ1djk2RUxBdzhlaFIyY3dEZ1lEVlIwUEFRSC9CQVFEQWdlQU1GMEdBMVVkRWdSV01GU0dVbWgwZEhCek9pOHZaMmwwYUhWaUxtTnZiUzlsZFMxa2FXZHBkR0ZzTFdsa1pXNTBhWFI1TFhkaGJHeGxkQzloY21Ob2FYUmxZM1IxY21VdFlXNWtMWEpsWm1WeVpXNWpaUzFtY21GdFpYZHZjbXN3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQUpOUy9ZdTZEcEM5VWlYTVdDUnQ4dG1QNFV3VnRQcEdXYnhjSWF3OFVVQ0tBaUVBczJkTUJ4cDAvcy90SC9tTWFWQSt0MWFtVFdLUDJBMzdVUDlzN1dmYVRpRT0iXX0.eyJfc2QiOiBbIjRUeENtRGFWZTFtLUdGS0V3Z3A0ZDBROGV1NWJWaWUyYmRuTEo5X0pQWDgiLCAiNGh6c3F2TFZMSUxxUDN4NWhsRHJjcEQxU2pCZUlNcF93QkQ2T2lFQUIxYyIsICI1azVKVzZVYUNuRGpVSjdXWU93T1dsVHRjSFlvRGJtbURHTDBBZjBEYlJrIiwgIjZwaXFFa1pkZWtjOHkwSnZGRTA1ZEVUSGdxcVpPU1RnVHBrZVI5bEFRWTgiLCAiVkdEVURkNi10bmFWYU9LS29CYnIyWVJIUGQzNjVGdmZJQkJpcnR2bzdXSSIsICJWaFF2NXIwbU9vTHVsRjFoMndoWkdkMFg5OWhoaHNJeTJzelZicW5yUjZjIiwgInJhLWY0WGd4OXdxRDF6R09Pc0tlTGt5RzJDTnVHU2FsZzlGaTNuek9EQjAiLCAic19nMS1Ha3Vyd2xuSWxGVWZlNVJXWGVCSmVNbEZFOFkzYlk3YUpsU29uQSIsICJ4dVhXajJNclQ2djZNVTJJMWpjX3ZkVXphYjlhRDh5YzRnNmtHQUR2eDRRIl0sICJpc3MiOiAiaHR0cHM6Ly9iYWNrZW5kLmV1ZGl3LmFydGUucHJvamouZXUiLCAiaWF0IjogMTc2NTQxMTIwMCwgImV4cCI6IDE3NzMxODcyMDAsICJ2Y3QiOiAidXJuOmV1ZGk6cGlkOjEiLCAic3RhdHVzIjogeyJpZGVudGlmaWVyX2xpc3QiOiB7ImlkIjogIjYwNzMiLCAidXJpIjogImh0dHBzOi8vYmFja2VuZC5ldWRpdy5hcnRlLnByb2pqLmV1L2lkZW50aWZpZXJfbGlzdC9GQy91cm46ZXVkaTpwaWQ6MS8xNmQ0ZDg4Zi1lYWU2LTQzYjctOWQwMy02MDE4OTY1Mzk2YWEifSwgInN0YXR1c19saXN0IjogeyJpZHgiOiA2MDczLCAidXJpIjogImh0dHBzOi8vYmFja2VuZC5ldWRpdy5hcnRlLnByb2pqLmV1L3Rva2VuX3N0YXR1c19saXN0L0ZDL3VybjpldWRpOnBpZDoxLzE2ZDRkODhmLWVhZTYtNDNiNy05ZDAzLTYwMTg5NjUzOTZhYSJ9fSwgIl9zZF9hbGciOiAic2hhLTI1NiIsICJjbmYiOiB7Imp3ayI6IHsia3R5IjogIkVDIiwgImNydiI6ICJQLTI1NiIsICJ4IjogInBzdXpkOHNqZklqTHVUYTRiNTktanpZT3BwbUE2US1zMnRPbmgwek9OT1UiLCAieSI6ICJWVVhId2pVR0FhTE91QWpzZC02bGlLTjFwVkE5X1E2RHo2Ri1nbDJfS05RIn19fQ.FXz_WcDDyjycFtkGRnIrNuQtg-0AB6GRqq7FAdFi1San1XJaOPu4XdrXeDleZ7TMGHrYW5ErydXv-_1Z5bjgZA~WyJUNVhRcXktZkdmS1Y5VnNyRVI4RXNBIiwgIlB0Il0~WyJTRS1sS3pENlEwOGF2TVVmN2lON1dnIiwgImNvdW50cnkiLCAiUHQiXQ~WyJ6S2FQeDlJQ0RXNDFWUzdEbFcwam9RIiwgImdpdmVuX25hbWUiLCAiQW5hIl0~WyJ6ZklYblJsMHNKYkVXLWZFQ2JOX1pBIiwgImZhbWlseV9uYW1lIiwgIkdyYWNhIl0~WyJ5cE9IaDVrb19FWExURU9YX2VIN0pBIiwgInBsYWNlX29mX2JpcnRoIiwgeyJfc2QiOiBbIjlTbkJSQ1lFbWNYQlNBZnVQUWZwdWw5MjhoQ1NoRlFJX1U3Tm1zbW51eTAiLCAiUFdyWC13alplTzFMYUw5LTU5cU1NU0RxWE9tRHJjLUZ4bkV2TVFzeEQ5ayIsICJiVDNMNkl3QUtqOHR5TG1vRXFTbFpWa3UtazZmTzM2dlBMcm5iNkxNMEVrIl19XQ~WyJjbXZIdF93UjMwQ2RVNzRORzlQVHR3IiwgIm5hdGlvbmFsaXRpZXMiLCBbeyIuLi4iOiAiLWoxdG55YmwybDBuR195YlpIdEFsM3ZjdURTWF9aLUZfLW5qWWxhRzZDYyJ9XV0~WyJTVllQVGVPRksyT3FtWVRGVHJ0ejVBIiwgInJlZ2lvbiIsICJMeCJd~WyJMSzdzTjktUFl3QWZ4T1dMVWtnbjV3IiwgImxvY2FsaXR5IiwgIkx4Il0~WyJZcmRfdUtoMVdyR1N0RFF0dlNaVXBnIiwgImJpcnRoZGF0ZSIsICIxOTg0LTEyLTExIl0~eyJhbGciOiJFUzI1NiIsInR5cCI6ImtiK2p3dCJ9.eyJub25jZSI6IjVlZjg3MWY5LTk1MjEtNDMxNC1iNDczLTYwMDAzZDUwZWFjNiIsInNkX2hhc2giOiJiVlZIWjQtWjJDajNTZmlQYnJoU3FidkZmV0p4cnhvRkxNVGdoanFob3VVIiwiaWF0IjoxNzY1NDU3MDA2LCJhdWQiOiJ4NTA5X3Nhbl9kbnM6ZGVtby1icnVrZXJzdGVkLnRlc3QuZWlkYXMyc2FuZGthc3NlLm5ldCJ9.TY7geWo4WL4L-ASwM0gTS22B2hb_YMjRgzbiOTWNfHt3Te6iFxSnPn1r-Cs8gF322kLc332hmsXGPw67ONgYzg";
            Exception e = assertThrows(Exception.class, () -> openID4VPResponseService.handleSDJwt(vpToken));
            assertEquals("Invalid selective disclosure", e.getMessage());
        }

        @DisplayName("from norway is the expected selective disclosure element with content")
        @Test
        public void retrieveClaimsFromSDJwtCredential_norway() throws Exception {
            final String vpToken = "eyJhbGciOiJFUzI1NiIsInR5cCI6ImRjK3NkLWp3dCIsIng1YyI6WyJNSUlEQ2pDQ0FyQ2dBd0lCQWdJSUtwR0xkTlp2T1RBd0NnWUlLb1pJemowRUF3SXdnWWN4SGpBY0JnTlZCR0VURlU1VVVrNVBMVTVQUms5U0xqazVNVGd5TlRneU56RUxNQWtHQTFVRUJoTUNUazh4SkRBaUJnTlZCQW9URzBSSlIwbFVRVXhKVTBWU1NVNUhVMFJKVWtWTFZFOVNRVlJGVkRFeU1EQUdBMVVFQXhNcFpXbGtZWE15YzJGdVpHdGhjM05sSUVWQlFTQlFjbTkyYVdSbGNpQkRRU0F5SUhONWMzUmxjM1F3SGhjTk1qWXdOREk0TVRFeE1UUXdXaGNOTWpjd05ESTRNVEV4TVRRd1dqQnBNUXN3Q1FZRFZRUUdFd0pPVHpFa01DSUdBMVVFQ2d3YlJFbEhTVlJCVEVsVFJWSkpUa2RUUkVsU1JVdFVUMUpCVkVWVU1SUXdFZ1lEVlFRRERBdENaWFpwYzNCdmNuUmxiakVlTUJ3R0ExVUVZUXdWVGxSU1RrOHRUazlHVDFJdU9Ua3hPREkxT0RJM01Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRWJEVmdHK2tuenpOT3Bxa2gyejJ3eTZXQkZ5MHRzRzUzOHIyMW9nbUVGeHdRaFg0Tnlta203U2ZCVmRhUyt6YXVjdERERER0czBhNnRyNWZZTlJwWmpLT0NBU0V3Z2dFZE1COEdBMVVkSXdRWU1CYUFGS1RaSzBLK3h1VXEwdSthdFpRRlV3Z2FoSGg0TUIwR0ExVWREZ1FXQkJURjE0cnltTTZYM1ZpZnNCa3V5bTAzdGpUUDdqQU1CZ05WSFJNQkFmOEVBakFBTUZnR0ExVWRId1JSTUU4d1RhQkxvRW1HUjJoMGRIQnpPaTh2WTJFdVpXbGtZWE15YzJGdVpHdGhjM05sTG1SbGRpOTJNUzlqWlhKMGN5OXBiblJsY20xbFpHbGhkR1Z6TDJWaFlWOXdjbTkyYVdSbGNqSXVZM0pzTUdNR0NDc0dBUVVGQndFQkJGY3dWVEJUQmdnckJnRUZCUWN3QW9aSGFIUjBjSE02THk5allTNWxhV1JoY3pKellXNWthMkZ6YzJVdVpHVjJMM1l4TDJObGNuUnpMMmx1ZEdWeWJXVmthV0YwWlhNdlpXRmhYM0J5YjNacFpHVnlNaTVqWlhJd0RnWURWUjBQQVFIL0JBUURBZ1dnTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSUNoWGgxcjRDbHgwY3YrckdDNkJaWUF5SXRXQVRVMUNsRDhJRVJ1VEM0czJBaUVBdDRtS0VUN1NYaHVNdlZZNHNoMWJaeTl5V2VnMHFHMGpuNUcvT2J3Y2Q1bz0iXX0.eyJfc2QiOlsicG8yWktrcmVwVmN4dmdXdDdLNjlscmdTQTltc2NJaWtpZ0hzYXY3aUdZZyIsImZ3bUVPQ2Z1X2QyRUE1VTdGcW5aeGg0Vzh6VHFqUUQzRVJscXhuMmJUd3MiLCJVQVktRzFoWFlPa3Y4NXp3OW1EeXl5VTBlejYxZnIwenVQcWRlVVd2dEtvIl0sInZjdCI6Im5vOmtvbnRha3RyZWdpc3RlcmV0OmtvbnRha3RpbmZvcm1hc2pvbjoxIiwiX3NkX2FsZyI6InNoYS0yNTYiLCJpc3MiOiJodHRwczovL3V0c3RlZGVyLmVpZGFzMnNhbmRrYXNzZS5kZXYvYmV2aXNnZW5lcmF0b3IiLCJjbmYiOnsiandrIjp7Imt0eSI6IkVDIiwiY3J2IjoiUC0yNTYiLCJ4IjoiVDRGWVZJeS1vVVM1SWFZbHpwVE81TXZNdEVfVEhXQlFpeGtYZ2FOa0pscyIsInkiOiJpMGlMQi1iRUNBT090c1g0WWQ4Yk1VcXV1LUVqWkJQNjVTemx4a0xuRV93In19LCJleHAiOjE4MDk0MTM5NTgsImlhdCI6MTc3Nzg3Nzk1OCwic3RhdHVzIjp7InN0YXR1c19saXN0Ijp7ImlkeCI6MjY5MjQwLCJ1cmkiOiJodHRwczovL3N0YXR1cy5laWRhczJzYW5ka2Fzc2UuZGV2L2xpc3RzLzEifX19.B2S6ierAGIMMpF89DkhQDJTZWXVWXUyfZtAgHPAeN83jDFuXLsmzg0pLws2vEfkhW--dtewsSNOwVcphTqTAdQ~WyJGc2IxYm5objRUbV93aTFja2V6MnhRIiwiZXBvc3RhZHJlc3NlIiwibnVsbHN0aWx0QGFsdGlubi54eXoiXQ~WyIzU21wS2VWcEY0cG1fbGNKVkZiV0J3IiwicGVyc29uaWRlbnRpZmlrYXRvciIsIjE2OTAzMzQ5ODQ0Il0~WyIxY0lzZUpSSk85eENwZHRtMnAzSHRnIiwibW9iaWx0ZWxlZm9ubnVtbWVyIiwiKzQ3NDg5OTU4NTUiXQ~eyJ0eXAiOiJrYitqd3QiLCJhbGciOiJFUzI1NiJ9.eyJzZF9oYXNoIjoiQXl3a0pBTEdwUFQ2MC1zOElPa3BPZHpIMUpWcGNDeldZcFZLTkptd1JjNCIsImF1ZCI6Ing1MDlfaGFzaDpiQkFWeDRISFVEWXJCbW90WEZXMTFzMzdUaExwUV9xUnFSR2ZzQVlnLThnIiwibm9uY2UiOiJhYzkzYjY1Zi1hZTZjLTQ2MjYtOGEzOS0wNDQyYmZkNmEwY2IiLCJpYXQiOjE3NzkxODQ2NzF9.nm3DZGtHogv82wu22ySQiGutwGyngBB76TImnQ_MJLtQrBBDZMD673XSyuhpLiMdh6dAWxTmVyiTamS8N7uPEw";
            // Parses a mock JWT just so it does not return null from tokenStatusListService.
            Mockito.when(tokenStatusListService.requestStatusList(URI.create("https://status.eidas2sandkasse.dev/lists/1"))).thenReturn(SignedJWT.parse("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30"));
            no.idporten.eudiw.demo.verifier.openid4vp.VerifiedCredentials verifiedCredentials = openID4VPResponseService.handleSDJwt(vpToken);
            assertEquals("nullstilt@altinn.xyz", verifiedCredentials.credentials().get("epostadresse"));
        }

        @DisplayName("from norway vp token the statuslist is included in token, and then it is sent to the service (sdjwt)")
        @Test
        void testExtractedStatusListUri() throws Exception {
            final String vpToken = "eyJhbGciOiJFUzI1NiIsInR5cCI6ImRjK3NkLWp3dCIsIng1YyI6WyJNSUlEQ2pDQ0FyQ2dBd0lCQWdJSUtwR0xkTlp2T1RBd0NnWUlLb1pJemowRUF3SXdnWWN4SGpBY0JnTlZCR0VURlU1VVVrNVBMVTVQUms5U0xqazVNVGd5TlRneU56RUxNQWtHQTFVRUJoTUNUazh4SkRBaUJnTlZCQW9URzBSSlIwbFVRVXhKVTBWU1NVNUhVMFJKVWtWTFZFOVNRVlJGVkRFeU1EQUdBMVVFQXhNcFpXbGtZWE15YzJGdVpHdGhjM05sSUVWQlFTQlFjbTkyYVdSbGNpQkRRU0F5SUhONWMzUmxjM1F3SGhjTk1qWXdOREk0TVRFeE1UUXdXaGNOTWpjd05ESTRNVEV4TVRRd1dqQnBNUXN3Q1FZRFZRUUdFd0pPVHpFa01DSUdBMVVFQ2d3YlJFbEhTVlJCVEVsVFJWSkpUa2RUUkVsU1JVdFVUMUpCVkVWVU1SUXdFZ1lEVlFRRERBdENaWFpwYzNCdmNuUmxiakVlTUJ3R0ExVUVZUXdWVGxSU1RrOHRUazlHVDFJdU9Ua3hPREkxT0RJM01Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRWJEVmdHK2tuenpOT3Bxa2gyejJ3eTZXQkZ5MHRzRzUzOHIyMW9nbUVGeHdRaFg0Tnlta203U2ZCVmRhUyt6YXVjdERERER0czBhNnRyNWZZTlJwWmpLT0NBU0V3Z2dFZE1COEdBMVVkSXdRWU1CYUFGS1RaSzBLK3h1VXEwdSthdFpRRlV3Z2FoSGg0TUIwR0ExVWREZ1FXQkJURjE0cnltTTZYM1ZpZnNCa3V5bTAzdGpUUDdqQU1CZ05WSFJNQkFmOEVBakFBTUZnR0ExVWRId1JSTUU4d1RhQkxvRW1HUjJoMGRIQnpPaTh2WTJFdVpXbGtZWE15YzJGdVpHdGhjM05sTG1SbGRpOTJNUzlqWlhKMGN5OXBiblJsY20xbFpHbGhkR1Z6TDJWaFlWOXdjbTkyYVdSbGNqSXVZM0pzTUdNR0NDc0dBUVVGQndFQkJGY3dWVEJUQmdnckJnRUZCUWN3QW9aSGFIUjBjSE02THk5allTNWxhV1JoY3pKellXNWthMkZ6YzJVdVpHVjJMM1l4TDJObGNuUnpMMmx1ZEdWeWJXVmthV0YwWlhNdlpXRmhYM0J5YjNacFpHVnlNaTVqWlhJd0RnWURWUjBQQVFIL0JBUURBZ1dnTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSUNoWGgxcjRDbHgwY3YrckdDNkJaWUF5SXRXQVRVMUNsRDhJRVJ1VEM0czJBaUVBdDRtS0VUN1NYaHVNdlZZNHNoMWJaeTl5V2VnMHFHMGpuNUcvT2J3Y2Q1bz0iXX0.eyJfc2QiOlsicG8yWktrcmVwVmN4dmdXdDdLNjlscmdTQTltc2NJaWtpZ0hzYXY3aUdZZyIsImZ3bUVPQ2Z1X2QyRUE1VTdGcW5aeGg0Vzh6VHFqUUQzRVJscXhuMmJUd3MiLCJVQVktRzFoWFlPa3Y4NXp3OW1EeXl5VTBlejYxZnIwenVQcWRlVVd2dEtvIl0sInZjdCI6Im5vOmtvbnRha3RyZWdpc3RlcmV0OmtvbnRha3RpbmZvcm1hc2pvbjoxIiwiX3NkX2FsZyI6InNoYS0yNTYiLCJpc3MiOiJodHRwczovL3V0c3RlZGVyLmVpZGFzMnNhbmRrYXNzZS5kZXYvYmV2aXNnZW5lcmF0b3IiLCJjbmYiOnsiandrIjp7Imt0eSI6IkVDIiwiY3J2IjoiUC0yNTYiLCJ4IjoiVDRGWVZJeS1vVVM1SWFZbHpwVE81TXZNdEVfVEhXQlFpeGtYZ2FOa0pscyIsInkiOiJpMGlMQi1iRUNBT090c1g0WWQ4Yk1VcXV1LUVqWkJQNjVTemx4a0xuRV93In19LCJleHAiOjE4MDk0MTM5NTgsImlhdCI6MTc3Nzg3Nzk1OCwic3RhdHVzIjp7InN0YXR1c19saXN0Ijp7ImlkeCI6MjY5MjQwLCJ1cmkiOiJodHRwczovL3N0YXR1cy5laWRhczJzYW5ka2Fzc2UuZGV2L2xpc3RzLzEifX19.B2S6ierAGIMMpF89DkhQDJTZWXVWXUyfZtAgHPAeN83jDFuXLsmzg0pLws2vEfkhW--dtewsSNOwVcphTqTAdQ~WyJGc2IxYm5objRUbV93aTFja2V6MnhRIiwiZXBvc3RhZHJlc3NlIiwibnVsbHN0aWx0QGFsdGlubi54eXoiXQ~WyIzU21wS2VWcEY0cG1fbGNKVkZiV0J3IiwicGVyc29uaWRlbnRpZmlrYXRvciIsIjE2OTAzMzQ5ODQ0Il0~WyIxY0lzZUpSSk85eENwZHRtMnAzSHRnIiwibW9iaWx0ZWxlZm9ubnVtbWVyIiwiKzQ3NDg5OTU4NTUiXQ~eyJ0eXAiOiJrYitqd3QiLCJhbGciOiJFUzI1NiJ9.eyJzZF9oYXNoIjoiQXl3a0pBTEdwUFQ2MC1zOElPa3BPZHpIMUpWcGNDeldZcFZLTkptd1JjNCIsImF1ZCI6Ing1MDlfaGFzaDpiQkFWeDRISFVEWXJCbW90WEZXMTFzMzdUaExwUV9xUnFSR2ZzQVlnLThnIiwibm9uY2UiOiJhYzkzYjY1Zi1hZTZjLTQ2MjYtOGEzOS0wNDQyYmZkNmEwY2IiLCJpYXQiOjE3NzkxODQ2NzF9.nm3DZGtHogv82wu22ySQiGutwGyngBB76TImnQ_MJLtQrBBDZMD673XSyuhpLiMdh6dAWxTmVyiTamS8N7uPEw";

            ArgumentCaptor<URI> captor = ArgumentCaptor.forClass(URI.class);

            // Parses a mock JWT just so it does not return null from tokenStatusListService.
            Mockito.when(tokenStatusListService.requestStatusList(URI.create("https://status.eidas2sandkasse.dev/lists/1"))).thenReturn(SignedJWT.parse("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30"));
            openID4VPResponseService.handleSDJwt(vpToken);

            Mockito.verify(tokenStatusListService)
                    .requestStatusList(captor.capture());

            URI capturedUri = captor.getValue();

            Assertions.assertEquals(URI.create("https://status.eidas2sandkasse.dev/lists/1"), capturedUri);
        }

        @DisplayName("from norway vp token the statuslist is included in token, and then it is sent to the service (MDoc)")
        @Test
        void testVerificationStatusMDoc() throws Exception {
            final String vpToken = "o2d2ZXJzaW9uYzEuMGlkb2N1bWVudHOBo2dkb2NUeXBleCZuby5hZHZva2F0dGlsc3luZXQuYWR2b2thdHJlZ2lzdGVyZXQuMWxpc3N1ZXJTaWduZWSiam5hbWVTcGFjZXOheCZuby5hZHZva2F0dGlsc3luZXQuYWR2b2thdHJlZ2lzdGVyZXQuMYXYGFhQpGhkaWdlc3RJRABmcmFuZG9tUJ-KBT27FTxYCGxkAJz0XIpxZWxlbWVudElkZW50aWZpZXJpZXR0ZXJuYXZubGVsZW1lbnRWYWx1ZWNGT1TYGFhipGhkaWdlc3RJRAFmcmFuZG9tUGUBys3CsoL3T139wApmSxVxZWxlbWVudElkZW50aWZpZXJnZm9ybmF2bmxlbGVtZW50VmFsdWV3w5hLT05PTUlTSyBJTklUSUFUSVZSSUvYGFhipGhkaWdlc3RJRAJmcmFuZG9tUH95vGyLAM0oRYuy9m31ujNxZWxlbWVudElkZW50aWZpZXJzcGVyc29uaWRlbnRpZmlrYXRvcmxlbGVtZW50VmFsdWVrMTY5MDMzNDk4NDTYGFhOpGhkaWdlc3RJRANmcmFuZG9tUAzPDHwtkx4kmiOlmdNqd8BxZWxlbWVudElkZW50aWZpZXJlcmVnbnJsZWxlbWVudFZhbHVlZTQ3NzU22BhYUaRoZGlnZXN0SUQEZnJhbmRvbVB8zpDkrGfIri1wdRMti61icWVsZW1lbnRJZGVudGlmaWVyZnRpdHRlbGxlbGVtZW50VmFsdWVnQWR2b2thdGppc3N1ZXJBdXRohEOhASahGCFZAw4wggMKMIICsKADAgECAggqkYt01m85MDAKBggqhkjOPQQDAjCBhzEeMBwGA1UEYRMVTlRSTk8tTk9GT1IuOTkxODI1ODI3MQswCQYDVQQGEwJOTzEkMCIGA1UEChMbRElHSVRBTElTRVJJTkdTRElSRUtUT1JBVEVUMTIwMAYDVQQDEyllaWRhczJzYW5ka2Fzc2UgRUFBIFByb3ZpZGVyIENBIDIgc3lzdGVzdDAeFw0yNjA0MjgxMTExNDBaFw0yNzA0MjgxMTExNDBaMGkxCzAJBgNVBAYTAk5PMSQwIgYDVQQKDBtESUdJVEFMSVNFUklOR1NESVJFS1RPUkFURVQxFDASBgNVBAMMC0JldmlzcG9ydGVuMR4wHAYDVQRhDBVOVFJOTy1OT0ZPUi45OTE4MjU4MjcwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARsNWAb6SfPM06mqSHbPbDLpYEXLS2wbnfyvbWiCYQXHBCFfg3KaSbtJ8FV1pL7Nq5y0MMMO2zRrq2vl9g1GlmMo4IBITCCAR0wHwYDVR0jBBgwFoAUpNkrQr7G5SrS75q1lAVTCBqEeHgwHQYDVR0OBBYEFMXXivKYzpfdWJ-wGS7KbTe2NM_uMAwGA1UdEwEB_wQCMAAwWAYDVR0fBFEwTzBNoEugSYZHaHR0cHM6Ly9jYS5laWRhczJzYW5ka2Fzc2UuZGV2L3YxL2NlcnRzL2ludGVybWVkaWF0ZXMvZWFhX3Byb3ZpZGVyMi5jcmwwYwYIKwYBBQUHAQEEVzBVMFMGCCsGAQUFBzAChkdodHRwczovL2NhLmVpZGFzMnNhbmRrYXNzZS5kZXYvdjEvY2VydHMvaW50ZXJtZWRpYXRlcy9lYWFfcHJvdmlkZXIyLmNlcjAOBgNVHQ8BAf8EBAMCBaAwCgYIKoZIzj0EAwIDSAAwRQIgKFeHWvgKXHRy_6sYLoFlgDIi1YBNTUKUPwgRG5MLizYCIQC3iYoRPtJeG4y9VjiyHVtnL3JZ6DSobSOfkb85vBx3mlkCl9gYWQKSp2d2ZXJzaW9uYzEuMG9kaWdlc3RBbGdvcml0aG1nU0hBLTI1Nmx2YWx1ZURpZ2VzdHOheCZuby5hZHZva2F0dGlsc3luZXQuYWR2b2thdHJlZ2lzdGVyZXQuMaUAWCCPkZMk4jIq-L-L9f2br-yAkmddGbPIaPdrcUq0WUyY8QFYIBQZ4fOuBE3sW3QAfEAzmdWbiNmDaMQYRuadYMKX0YtgAlggO-DOkwGTsabTAlfY2nW2OZM6_woyRcs-ploKMgQp2iwDWCAbVPQ07ycDSmfUvuPI_BZiLwr0dBcbtPTcadYE5N4n2gRYINxdUSwHrUOwZxOwUzlRkbE2c8peoI6dWIzetnsHAc6wbWRldmljZUtleUluZm-haWRldmljZUtleaQBAiABIVggu7mTsSdBfqjO96wp5ZL7pBXx4JlANjsael9IsDfW-zciWCBwB-2goxqY_rxntl-aoEOrfdFqDgrPExSJl_SLBqKfJGdkb2NUeXBleCZuby5hZHZva2F0dGlsc3luZXQuYWR2b2thdHJlZ2lzdGVyZXQuMWx2YWxpZGl0eUluZm-kZnNpZ25lZMB4GDIwMjYtMDYtMTBUMDg6NDA6MjguMDE2Wml2YWxpZEZyb23AeBgyMDI2LTA2LTEwVDA4OjQwOjI4LjAxNlpqdmFsaWRVbnRpbMB4GDIwMjctMDYtMTBUMDg6NDE6MjguMDE2Wm5leHBlY3RlZFVwZGF0ZcB4GDIwMjctMDYtMTBUMDg6NDE6MjguMDE2WmZzdGF0dXOha3N0YXR1c19saXN0omNpZHgaAAV-wmN1cml4Kmh0dHBzOi8vc3RhdHVzLmVpZGFzMnNhbmRrYXNzZS5kZXYvbGlzdHMvMVhAz5TC8AtTNnfPrpnxWaLYtdbYBoD_ouKSmtWrl-725RGk4pby-z58rvUAgIrirFd8VMvl2myBuyM4CBU1ynQB2WxkZXZpY2VTaWduZWSiam5hbWVTcGFjZXPYGEGgamRldmljZUF1dGihb2RldmljZVNpZ25hdHVyZYRDoQEmoPZYQJgkNpndq1d1X5cuKIXeodgE3S4bZwsbN0Oueg2OA9uj4OJXPg16RNZZX2iakhv_uRMJ_tZt51y3odQyB9YaGk1mc3RhdHVzAA";

            ArgumentCaptor<URI> captor = ArgumentCaptor.forClass(URI.class);

            // Parses a mock JWT just so it does not return null from tokenStatusListService.
            Mockito.when(tokenStatusListService.requestStatusList(URI.create("https://status.eidas2sandkasse.dev/lists/1"))).thenReturn(SignedJWT.parse("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30"));
            openID4VPResponseService.handleMDoc(vpToken);

            Mockito.verify(tokenStatusListService)
                    .requestStatusList(captor.capture());

            URI capturedUri = captor.getValue();

            Assertions.assertEquals(URI.create("https://status.eidas2sandkasse.dev/lists/1"), capturedUri);
        }

        @DisplayName("from norway vp token the statuslist is NOT included in token, and then it is a valid proof (sdjwt)")
        @Test
        void testExtractedStatusListUriWhenStatusDoesNotExist() throws Exception {

            final String vpToken = "eyJhbGciOiJFUzI1NiIsInR5cCI6ImRjK3NkLWp3dCIsIng1YyI6WyJNSUlETURDQ0F0ZWdBd0lCQWdJSkFQSTNtNW9DdkVoak1Bb0dDQ3FHU000OUJBTUNNSUdFTVI0d0hBWURWUVJoRXhWT1ZGSk9UeTFPVDBaUFVpNDVPVEU0TWpVNE1qY3hDekFKQmdOVkJBWVRBazVQTVNRd0lnWURWUVFLRXh0RVNVZEpWRUZNU1ZORlVrbE9SMU5FU1ZKRlMxUlBVa0ZVUlZReEx6QXRCZ05WQkFNVEptVnBaR0Z6TW5OaGJtUnJZWE56WlNCRlFVRWdVSEp2ZG1sa1pYSWdRMEVnTWlCMFpYTjBNQjRYRFRJMk1EUXlPREV4TVRneU5Wb1hEVEkzTURReU9ERXhNVGd5TlZvd2dZY3hDekFKQmdOVkJBWVRBazVQTVNRd0lnWURWUVFLREJ0RVNVZEpWRUZNU1ZORlVrbE9SMU5FU1ZKRlMxUlBVa0ZVUlZReE1qQXdCZ05WQkFNTUtVUnBaMmwwWVd4cGMyVnlhVzVuYzJScGNtVnJkRzl5WVhSbGRDQXRJRUpsZG1semNHOXlkR1Z1TVI0d0hBWURWUVJoREJWT1ZGSk9UeTFPVDBaUFVpNDVPVEU0TWpVNE1qY3dXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBVDc1Z3NxdEtrL1BpTXZVMmkyalRFTXo0aEduQkhPdHBSQ2JFTDBFeklhSFBWRS9wdGVTaldtL1czQ3BoT1hiMXV5Ukt2Y1ByaGdtazFLRTdaV3MyaHBvNElCS3pDQ0FTY3dId1lEVlIwakJCZ3dGb0FVTVJURXBzaThZdU53WVRsTVdHcmhCUitFais4d0hRWURWUjBPQkJZRUZMdmc5KzlRaVU3NWpGb3dKenEwVzlUVzBQOWlNQXdHQTFVZEV3RUIvd1FDTUFBd1hRWURWUjBmQkZZd1ZEQlNvRkNnVG9aTWFIUjBjSE02THk5allTNTBaWE4wTG1WcFpHRnpNbk5oYm1ScllYTnpaUzV1WlhRdmRqRXZZMlZ5ZEhNdmFXNTBaWEp0WldScFlYUmxjeTlsWVdGZmNISnZkbWxrWlhJeUxtTnliREJvQmdnckJnRUZCUWNCQVFSY01Gb3dXQVlJS3dZQkJRVUhNQUtHVEdoMGRIQnpPaTh2WTJFdWRHVnpkQzVsYVdSaGN6SnpZVzVrYTJGemMyVXVibVYwTDNZeEwyTmxjblJ6TDJsdWRHVnliV1ZrYVdGMFpYTXZaV0ZoWDNCeWIzWnBaR1Z5TWk1alpYSXdEZ1lEVlIwUEFRSC9CQVFEQWdXZ01Bb0dDQ3FHU000OUJBTUNBMGNBTUVRQ0lENGZLV0E0STNtSHhEZ3RhSmtzdmk3SVJBSHFPbWpjOTJ6OFV5VndQbGdvQWlCaWo2WUhNdXB4QXQ1eXZraTVmczZiV0kvNHNMd2tmWUlYZ3ZTWFVHL0Zvdz09Il19.eyJfc2QiOlsiTUx6M3dJTVRnekRoSjZMdEt6anhMY0F3MzAzZFdObzNwZDh1N1NUb1hqRSIsImk2NDhxcjkxT3Y0Z3ZRak9BbDk0ajBhYnFqWWM1TmJFLTRtb3pjOFM1eEEiLCJGZ2pCbGtxMk1ILUdVMDNCa1dUQndwTzVHcDUzWTJ1M0Q2bEJJWDhSLXdvIl0sInZjdCI6Im5vOmtvbnRha3RyZWdpc3RlcmV0OmtvbnRha3RpbmZvcm1hc2pvbjoxIiwiX3NkX2FsZyI6InNoYS0yNTYiLCJpc3MiOiJodHRwczovL3V0c3RlZGVyLnRlc3QuZWlkYXMyc2FuZGthc3NlLm5ldC9iZXZpc2dlbmVyYXRvciIsImNuZiI6eyJqd2siOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIzMHdxVElPVTVhNmloN1p1bWRUTldQVGpTLTh2NkM3WlhNM3BPaTJ6QVhFIiwieSI6IkQ2eE9idC1JQzRzLTd6S1ZSdTEySG16VnNHbnFKYnlFSXlMa25yNVJtRm8ifX0sImV4cCI6MTgwOTc4MDU0MywiaWF0IjoxNzc4MjQ0NTQzfQ.FShpSV1FmZ5U1t1ov8d3rWIjqHlwWrsx8ZDz7zBV-r43RzRscOStWgdG-z5-wHk4qH4NVzc_YvSqMXEIUW4krw~WyJNc09TUFhqZVk3Q1F2bndzWk12TXJBIiwiZXBvc3RhZHJlc3NlIiwibnVsbHN0aWx0QGFsdGlubi54eXoiXQ~WyIyLVdoVW9fNi00MHMwUlQwSlZQOTJnIiwicGVyc29uaWRlbnRpZmlrYXRvciIsIjE2OTAzMzQ5ODQ0Il0~WyI2b0hlR3JOeTlVX1BTNmEtc3hCejF3IiwibW9iaWx0ZWxlZm9ubnVtbWVyIiwiKzQ3NDg5OTU4NTUiXQ~eyJ0eXAiOiJrYitqd3QiLCJhbGciOiJFUzI1NiJ9.eyJzZF9oYXNoIjoieE9oUEhuYXBJYjdlV0J0bDJvSzRZbXdKcFNoOVVOYU1zeE9TRmFZWGdEbyIsImF1ZCI6Ing1MDlfaGFzaDpzNVNfZmxGNy1xYzV2Z20wdHdHclphQkF1MHpjYXg1WURrQ0g0ak5UUEdNIiwibm9uY2UiOiJiY2YyYjc2Zi1kNmMyLTQ5YmYtOWFmMi0wMmM2MDY3MjMxNGQiLCJpYXQiOjE3NzkyNzU3MzB9.RPS1ofMz1lKIIytLhimGn4t28JI_1rx4exhdODdepgpudpyAZbLabWTzpoIhvRci75cuF138zlHyIx5cBM2amg";

            no.idporten.eudiw.demo.verifier.openid4vp.VerifiedCredentials verifiedCredentials = openID4VPResponseService.handleSDJwt(vpToken);

            Mockito.verify(tokenStatusListService, Mockito.times(0)).requestStatusList(Mockito.any());

            assertEquals("nullstilt@altinn.xyz", verifiedCredentials.credentials().get("epostadresse"));
            assertEquals("VALID", verifiedCredentials.status().toString());

        }

        @DisplayName("from norway vp token the statuslist is NOT included in token, and then it is a valid proof (mdoc)")
        @Test
        void testCheckVerificationStatusWhenStatusDoesNotExist() throws Exception {

            final String vpToken = "o2d2ZXJzaW9uYzEuMGlkb2N1bWVudHOBo2dkb2NUeXBld2V1LmV1cm9wYS5lYy5ldWRpLnBpZC4xbGlzc3VlclNpZ25lZKJqbmFtZVNwYWNlc6F3ZXUuZXVyb3BhLmVjLmV1ZGkucGlkLjGF2BhYXqRoZGlnZXN0SUQCZnJhbmRvbVArjm9yHcVojT4hsh2lBSfycWVsZW1lbnRJZGVudGlmaWVya2ZhbWlseV9uYW1lbGVsZW1lbnRWYWx1ZW9GQVRUSUdNQU5OU0tPU1TYGFhdpGhkaWdlc3RJRAhmcmFuZG9tUC0jzw41ZkRpwUag673ExPtxZWxlbWVudElkZW50aWZpZXJucGxhY2Vfb2ZfYmlydGhsZWxlbWVudFZhbHVloWdjb3VudHJ5YlVa2BhYW6RoZGlnZXN0SUQAZnJhbmRvbVBr_XwBrYRPpvTxoMg7Q2-qcWVsZW1lbnRJZGVudGlmaWVyamJpcnRoX2RhdGVsZWxlbWVudFZhbHVl2QPsajIwMDMtMTItMzDYGFhWpGhkaWdlc3RJRANmcmFuZG9tUEc8TfczXiL0s2ilSu8VRc9xZWxlbWVudElkZW50aWZpZXJqZ2l2ZW5fbmFtZWxlbGVtZW50VmFsdWVoVVZJVEVOREXYGFhSpGhkaWdlc3RJRAZmcmFuZG9tUAsSAuWtTcmFJsK3CaOtVjpxZWxlbWVudElkZW50aWZpZXJrbmF0aW9uYWxpdHlsZWxlbWVudFZhbHVlgWJVWmppc3N1ZXJBdXRohEOhASahGCFZAw4wggMKMIICsaADAgECAggE-AwOi_QyETAKBggqhkjOPQQDAjCBhzEeMBwGA1UEYRMVTlRSTk8tTk9GT1IuOTkxODI1ODI3MQswCQYDVQQGEwJOTzEkMCIGA1UEChMbRElHSVRBTElTRVJJTkdTRElSRUtUT1JBVEVUMTIwMAYDVQQDEyllaWRhczJzYW5ka2Fzc2UgUElEIFByb3ZpZGVyIENBIDIgc3lzdGVzdDAeFw0yNjA0MjgxMDQxMTBaFw0yNzA0MjgxMDQxMTBaMGoxCzAJBgNVBAYTAk5PMSQwIgYDVQQKDBtESUdJVEFMSVNFUklOR1NESVJFS1RPUkFURVQxFTATBgNVBAMMDFBJRC11dHN0ZWRlcjEeMBwGA1UEYQwVTlRSTk8tTk9GT1IuOTkxODI1ODI3MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEBVeaLX6Y51hYevthgMin9MszZz6E-EJntiruG4C40DVtV7mUhguRPB7r9LLP5nl_ooS1P3taoE_UET1mQld8pKOCASEwggEdMB8GA1UdIwQYMBaAFLrwF_EbNDbV76s7JWGLqEq2C-pLMB0GA1UdDgQWBBSWx5OizEHkN2bdw9dasuEEk_V4cTAMBgNVHRMBAf8EAjAAMFgGA1UdHwRRME8wTaBLoEmGR2h0dHBzOi8vY2EuZWlkYXMyc2FuZGthc3NlLmRldi92MS9jZXJ0cy9pbnRlcm1lZGlhdGVzL3BpZF9wcm92aWRlcjIuY3JsMGMGCCsGAQUFBwEBBFcwVTBTBggrBgEFBQcwAoZHaHR0cHM6Ly9jYS5laWRhczJzYW5ka2Fzc2UuZGV2L3YxL2NlcnRzL2ludGVybWVkaWF0ZXMvcGlkX3Byb3ZpZGVyMi5jZXIwDgYDVR0PAQH_BAQDAgWgMAoGCCqGSM49BAMCA0cAMEQCIEM5W-AvWNg_C7SwYyPqHdz4l3P_k4zgeodaAuNHOUXlAiATFq7nXMRYdg42ioKmWASGmfuscbw-KfhTXiCs21IplFkCtdgYWQKwpmd2ZXJzaW9uYzEuMG9kaWdlc3RBbGdvcml0aG1nU0hBLTI1Nmx2YWx1ZURpZ2VzdHOhd2V1LmV1cm9wYS5lYy5ldWRpLnBpZC4xqQBYILT0tYF-nc_SZcyBv9diAA5s9DZmXUrsI2jmE2IkpzDgAVgguEVMf38Rs-xuork-QM6nCpYDN_98F9aKH-O3fs3TMMgCWCC-8FT-NGIR6BD8mYxRyZ68u5-EMrzJ_EaAZqJf0ETmeQNYIDzZvRbTcWrELniyjB7WdXN3jEFGTFzKkqD7ddxQVxMvBFggFl_Xi_KLpggvrn3G2YfsCa9GcircvJPSB7mklKL28EsFWCDwCJgLUL5ZPbWhy2sT3GczaAj6te1dCfEGGwH04tdwUAZYIMBOZJ-XsJTpRNYT4ypNezX1fAjFE-Bcj_hyevdxTN5iB1gg76OLrsOua3OZGE4c0u2Y-xJSjXmamGlGhQBbyDeiC5oIWCBaY31c-k4Zlo1g_bx4cmAEPYim8BnzYJm_D6LPLhkP8G1kZXZpY2VLZXlJbmZvoWlkZXZpY2VLZXmkAQIgASFYIArCsX3tS9dQ8DyFR2fUD9xku-uTvS2H27bsJr00pEQRIlgglchQI8CAN60r2Z23UGA8iTdkfrgkz2MhFmsqDWuqGhBnZG9jVHlwZXdldS5ldXJvcGEuZWMuZXVkaS5waWQuMWx2YWxpZGl0eUluZm-kZnNpZ25lZMB4GDIwMjYtMDYtMDlUMTE6MDI6MzguNjEwWml2YWxpZEZyb23AeBgyMDI2LTA2LTA5VDExOjAyOjM4LjYxMFpqdmFsaWRVbnRpbMB4GDIwMjctMDYtMDlUMTE6MDM6MzguNjEwWm5leHBlY3RlZFVwZGF0ZcB4GDIwMjctMDYtMDlUMTE6MDM6MzguNjEwWlhAYsCbwQ7Mt6Utc_v9VUBW7cLW3sLO6SPAACHVdTP5C20i_lXrh2YZUu8l6ypQC7artP9j355S85ymLxwXnYiY9mxkZXZpY2VTaWduZWSiam5hbWVTcGFjZXPYGEGgamRldmljZUF1dGihb2RldmljZVNpZ25hdHVyZYRDoQEmoPZYQIIsPeOa62h1GCMhOlzo5VaRlfZ-TxLs53EDS6pMyMWyw8IFa5FzqC46IlwFS6rDYoO-8H8-0XbpWSHKhYgfxvJmc3RhdHVzAA";

            no.idporten.eudiw.demo.verifier.openid4vp.VerifiedCredentials verifiedCredentials = openID4VPResponseService.handleMDoc(vpToken);

            Mockito.verify(tokenStatusListService, Mockito.times(0)).requestStatusList(Mockito.any());

            assertEquals("UVITENDE", verifiedCredentials.credentials().get("given_name"));
            assertEquals("VALID", verifiedCredentials.status().toString());

        }

        @DisplayName("from norway when StatusCommunicationException is thrown, the status is set to INCONCLUSIVE")
        @Test
        void testWhenStatusCommunicationExceptionIsThrownStatusIsInconclusive() throws Exception {
            // vp token with status attribute
            final String vpToken = "eyJhbGciOiJFUzI1NiIsInR5cCI6ImRjK3NkLWp3dCIsIng1YyI6WyJNSUlEQ2pDQ0FyQ2dBd0lCQWdJSUtwR0xkTlp2T1RBd0NnWUlLb1pJemowRUF3SXdnWWN4SGpBY0JnTlZCR0VURlU1VVVrNVBMVTVQUms5U0xqazVNVGd5TlRneU56RUxNQWtHQTFVRUJoTUNUazh4SkRBaUJnTlZCQW9URzBSSlIwbFVRVXhKVTBWU1NVNUhVMFJKVWtWTFZFOVNRVlJGVkRFeU1EQUdBMVVFQXhNcFpXbGtZWE15YzJGdVpHdGhjM05sSUVWQlFTQlFjbTkyYVdSbGNpQkRRU0F5SUhONWMzUmxjM1F3SGhjTk1qWXdOREk0TVRFeE1UUXdXaGNOTWpjd05ESTRNVEV4TVRRd1dqQnBNUXN3Q1FZRFZRUUdFd0pPVHpFa01DSUdBMVVFQ2d3YlJFbEhTVlJCVEVsVFJWSkpUa2RUUkVsU1JVdFVUMUpCVkVWVU1SUXdFZ1lEVlFRRERBdENaWFpwYzNCdmNuUmxiakVlTUJ3R0ExVUVZUXdWVGxSU1RrOHRUazlHVDFJdU9Ua3hPREkxT0RJM01Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRWJEVmdHK2tuenpOT3Bxa2gyejJ3eTZXQkZ5MHRzRzUzOHIyMW9nbUVGeHdRaFg0Tnlta203U2ZCVmRhUyt6YXVjdERERER0czBhNnRyNWZZTlJwWmpLT0NBU0V3Z2dFZE1COEdBMVVkSXdRWU1CYUFGS1RaSzBLK3h1VXEwdSthdFpRRlV3Z2FoSGg0TUIwR0ExVWREZ1FXQkJURjE0cnltTTZYM1ZpZnNCa3V5bTAzdGpUUDdqQU1CZ05WSFJNQkFmOEVBakFBTUZnR0ExVWRId1JSTUU4d1RhQkxvRW1HUjJoMGRIQnpPaTh2WTJFdVpXbGtZWE15YzJGdVpHdGhjM05sTG1SbGRpOTJNUzlqWlhKMGN5OXBiblJsY20xbFpHbGhkR1Z6TDJWaFlWOXdjbTkyYVdSbGNqSXVZM0pzTUdNR0NDc0dBUVVGQndFQkJGY3dWVEJUQmdnckJnRUZCUWN3QW9aSGFIUjBjSE02THk5allTNWxhV1JoY3pKellXNWthMkZ6YzJVdVpHVjJMM1l4TDJObGNuUnpMMmx1ZEdWeWJXVmthV0YwWlhNdlpXRmhYM0J5YjNacFpHVnlNaTVqWlhJd0RnWURWUjBQQVFIL0JBUURBZ1dnTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSUNoWGgxcjRDbHgwY3YrckdDNkJaWUF5SXRXQVRVMUNsRDhJRVJ1VEM0czJBaUVBdDRtS0VUN1NYaHVNdlZZNHNoMWJaeTl5V2VnMHFHMGpuNUcvT2J3Y2Q1bz0iXX0.eyJfc2QiOlsicG8yWktrcmVwVmN4dmdXdDdLNjlscmdTQTltc2NJaWtpZ0hzYXY3aUdZZyIsImZ3bUVPQ2Z1X2QyRUE1VTdGcW5aeGg0Vzh6VHFqUUQzRVJscXhuMmJUd3MiLCJVQVktRzFoWFlPa3Y4NXp3OW1EeXl5VTBlejYxZnIwenVQcWRlVVd2dEtvIl0sInZjdCI6Im5vOmtvbnRha3RyZWdpc3RlcmV0OmtvbnRha3RpbmZvcm1hc2pvbjoxIiwiX3NkX2FsZyI6InNoYS0yNTYiLCJpc3MiOiJodHRwczovL3V0c3RlZGVyLmVpZGFzMnNhbmRrYXNzZS5kZXYvYmV2aXNnZW5lcmF0b3IiLCJjbmYiOnsiandrIjp7Imt0eSI6IkVDIiwiY3J2IjoiUC0yNTYiLCJ4IjoiVDRGWVZJeS1vVVM1SWFZbHpwVE81TXZNdEVfVEhXQlFpeGtYZ2FOa0pscyIsInkiOiJpMGlMQi1iRUNBT090c1g0WWQ4Yk1VcXV1LUVqWkJQNjVTemx4a0xuRV93In19LCJleHAiOjE4MDk0MTM5NTgsImlhdCI6MTc3Nzg3Nzk1OCwic3RhdHVzIjp7InN0YXR1c19saXN0Ijp7ImlkeCI6MjY5MjQwLCJ1cmkiOiJodHRwczovL3N0YXR1cy5laWRhczJzYW5ka2Fzc2UuZGV2L2xpc3RzLzEifX19.B2S6ierAGIMMpF89DkhQDJTZWXVWXUyfZtAgHPAeN83jDFuXLsmzg0pLws2vEfkhW--dtewsSNOwVcphTqTAdQ~WyJGc2IxYm5objRUbV93aTFja2V6MnhRIiwiZXBvc3RhZHJlc3NlIiwibnVsbHN0aWx0QGFsdGlubi54eXoiXQ~WyIzU21wS2VWcEY0cG1fbGNKVkZiV0J3IiwicGVyc29uaWRlbnRpZmlrYXRvciIsIjE2OTAzMzQ5ODQ0Il0~WyIxY0lzZUpSSk85eENwZHRtMnAzSHRnIiwibW9iaWx0ZWxlZm9ubnVtbWVyIiwiKzQ3NDg5OTU4NTUiXQ~eyJ0eXAiOiJrYitqd3QiLCJhbGciOiJFUzI1NiJ9.eyJzZF9oYXNoIjoiQXl3a0pBTEdwUFQ2MC1zOElPa3BPZHpIMUpWcGNDeldZcFZLTkptd1JjNCIsImF1ZCI6Ing1MDlfaGFzaDpiQkFWeDRISFVEWXJCbW90WEZXMTFzMzdUaExwUV9xUnFSR2ZzQVlnLThnIiwibm9uY2UiOiJhYzkzYjY1Zi1hZTZjLTQ2MjYtOGEzOS0wNDQyYmZkNmEwY2IiLCJpYXQiOjE3NzkxODQ2NzF9.nm3DZGtHogv82wu22ySQiGutwGyngBB76TImnQ_MJLtQrBBDZMD673XSyuhpLiMdh6dAWxTmVyiTamS8N7uPEw";

            // Mock that exception for timeout is thrown inside requestStatusList method
            Mockito.when(tokenStatusListService.requestStatusList(URI.create("https://status.eidas2sandkasse.dev/lists/1"))).thenThrow(StatusCommunicationException.class);

            no.idporten.eudiw.demo.verifier.openid4vp.VerifiedCredentials verifiedCredentials = openID4VPResponseService.handleSDJwt(vpToken);

            // We still get and see the credentials, because demo verifier is a testing tool, but the result is inconclusive because of
            // issues communicating with status api
            assertEquals("nullstilt@altinn.xyz", verifiedCredentials.credentials().get("epostadresse"));
            assertEquals("INCONCLUSIVE", verifiedCredentials.status().toString());

        }

        @Test
        void krisetest() throws Exception {
            final String vpToken = "eyJhbGciOiJFUzI1NiIsInR5cCI6ImRjK3NkLWp3dCIsIng1YyI6WyJNSUlETURDQ0F0ZWdBd0lCQWdJSkFQSTNtNW9DdkVoak1Bb0dDQ3FHU000OUJBTUNNSUdFTVI0d0hBWURWUVJoRXhWT1ZGSk9UeTFPVDBaUFVpNDVPVEU0TWpVNE1qY3hDekFKQmdOVkJBWVRBazVQTVNRd0lnWURWUVFLRXh0RVNVZEpWRUZNU1ZORlVrbE9SMU5FU1ZKRlMxUlBVa0ZVUlZReEx6QXRCZ05WQkFNVEptVnBaR0Z6TW5OaGJtUnJZWE56WlNCRlFVRWdVSEp2ZG1sa1pYSWdRMEVnTWlCMFpYTjBNQjRYRFRJMk1EUXlPREV4TVRneU5Wb1hEVEkzTURReU9ERXhNVGd5TlZvd2dZY3hDekFKQmdOVkJBWVRBazVQTVNRd0lnWURWUVFLREJ0RVNVZEpWRUZNU1ZORlVrbE9SMU5FU1ZKRlMxUlBVa0ZVUlZReE1qQXdCZ05WQkFNTUtVUnBaMmwwWVd4cGMyVnlhVzVuYzJScGNtVnJkRzl5WVhSbGRDQXRJRUpsZG1semNHOXlkR1Z1TVI0d0hBWURWUVJoREJWT1ZGSk9UeTFPVDBaUFVpNDVPVEU0TWpVNE1qY3dXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBVDc1Z3NxdEtrL1BpTXZVMmkyalRFTXo0aEduQkhPdHBSQ2JFTDBFeklhSFBWRS9wdGVTaldtL1czQ3BoT1hiMXV5Ukt2Y1ByaGdtazFLRTdaV3MyaHBvNElCS3pDQ0FTY3dId1lEVlIwakJCZ3dGb0FVTVJURXBzaThZdU53WVRsTVdHcmhCUitFais4d0hRWURWUjBPQkJZRUZMdmc5KzlRaVU3NWpGb3dKenEwVzlUVzBQOWlNQXdHQTFVZEV3RUIvd1FDTUFBd1hRWURWUjBmQkZZd1ZEQlNvRkNnVG9aTWFIUjBjSE02THk5allTNTBaWE4wTG1WcFpHRnpNbk5oYm1ScllYTnpaUzV1WlhRdmRqRXZZMlZ5ZEhNdmFXNTBaWEp0WldScFlYUmxjeTlsWVdGZmNISnZkbWxrWlhJeUxtTnliREJvQmdnckJnRUZCUWNCQVFSY01Gb3dXQVlJS3dZQkJRVUhNQUtHVEdoMGRIQnpPaTh2WTJFdWRHVnpkQzVsYVdSaGN6SnpZVzVrYTJGemMyVXVibVYwTDNZeEwyTmxjblJ6TDJsdWRHVnliV1ZrYVdGMFpYTXZaV0ZoWDNCeWIzWnBaR1Z5TWk1alpYSXdEZ1lEVlIwUEFRSC9CQVFEQWdXZ01Bb0dDQ3FHU000OUJBTUNBMGNBTUVRQ0lENGZLV0E0STNtSHhEZ3RhSmtzdmk3SVJBSHFPbWpjOTJ6OFV5VndQbGdvQWlCaWo2WUhNdXB4QXQ1eXZraTVmczZiV0kvNHNMd2tmWUlYZ3ZTWFVHL0Zvdz09Il19.eyJfc2QiOlsiTUx6M3dJTVRnekRoSjZMdEt6anhMY0F3MzAzZFdObzNwZDh1N1NUb1hqRSIsImk2NDhxcjkxT3Y0Z3ZRak9BbDk0ajBhYnFqWWM1TmJFLTRtb3pjOFM1eEEiLCJGZ2pCbGtxMk1ILUdVMDNCa1dUQndwTzVHcDUzWTJ1M0Q2bEJJWDhSLXdvIl0sInZjdCI6Im5vOmtvbnRha3RyZWdpc3RlcmV0OmtvbnRha3RpbmZvcm1hc2pvbjoxIiwiX3NkX2FsZyI6InNoYS0yNTYiLCJpc3MiOiJodHRwczovL3V0c3RlZGVyLnRlc3QuZWlkYXMyc2FuZGthc3NlLm5ldC9iZXZpc2dlbmVyYXRvciIsImNuZiI6eyJqd2siOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiIzMHdxVElPVTVhNmloN1p1bWRUTldQVGpTLTh2NkM3WlhNM3BPaTJ6QVhFIiwieSI6IkQ2eE9idC1JQzRzLTd6S1ZSdTEySG16VnNHbnFKYnlFSXlMa25yNVJtRm8ifX0sImV4cCI6MTgwOTc4MDU0MywiaWF0IjoxNzc4MjQ0NTQzfQ.FShpSV1FmZ5U1t1ov8d3rWIjqHlwWrsx8ZDz7zBV-r43RzRscOStWgdG-z5-wHk4qH4NVzc_YvSqMXEIUW4krw~WyJNc09TUFhqZVk3Q1F2bndzWk12TXJBIiwiZXBvc3RhZHJlc3NlIiwibnVsbHN0aWx0QGFsdGlubi54eXoiXQ~WyIyLVdoVW9fNi00MHMwUlQwSlZQOTJnIiwicGVyc29uaWRlbnRpZmlrYXRvciIsIjE2OTAzMzQ5ODQ0Il0~WyI2b0hlR3JOeTlVX1BTNmEtc3hCejF3IiwibW9iaWx0ZWxlZm9ubnVtbWVyIiwiKzQ3NDg5OTU4NTUiXQ~eyJ0eXAiOiJrYitqd3QiLCJhbGciOiJFUzI1NiJ9.eyJzZF9oYXNoIjoieE9oUEhuYXBJYjdlV0J0bDJvSzRZbXdKcFNoOVVOYU1zeE9TRmFZWGdEbyIsImF1ZCI6Ing1MDlfaGFzaDpzNVNfZmxGNy1xYzV2Z20wdHdHclphQkF1MHpjYXg1WURrQ0g0ak5UUEdNIiwibm9uY2UiOiJiY2YyYjc2Zi1kNmMyLTQ5YmYtOWFmMi0wMmM2MDY3MjMxNGQiLCJpYXQiOjE3NzkyNzU3MzB9.RPS1ofMz1lKIIytLhimGn4t28JI_1rx4exhdODdepgpudpyAZbLabWTzpoIhvRci75cuF138zlHyIx5cBM2amg";
            claimsHelperMethod(vpToken);
        }


        Map<String, Object> claimsHelperMethod(String vpToken) throws Exception{
            id.walt.sdjwt.SDJwt unverifiedSDJwt = openID4VPResponseService.unverifiedSDJwt(vpToken);
            X509Certificate cert = openID4VPResponseService.certificate(unverifiedSDJwt);
            JWSVerifier jwsVerifier = openID4VPResponseService.jwsVerifier(cert);
            JWSAlgorithm jwsAlgorithm = openID4VPResponseService.algorithm(cert);
            SimpleJWTCryptoProvider cryptoProvider = new SimpleJWTCryptoProvider(jwsAlgorithm, null, jwsVerifier);
            VerificationResult<id.walt.sdjwt.SDJwt> result = openID4VPResponseService.verificationResult(cryptoProvider, unverifiedSDJwt);
            Map<String, Object> claims = openID4VPResponseService.retrieveClaimsFromSDJwtCredential(result);
            return claims;
        }

        VerificationResult<id.walt.sdjwt.SDJwt> verificationResultHelperMethod(String vpToken) throws Exception {
            id.walt.sdjwt.SDJwt unverifiedSDJwt = openID4VPResponseService.unverifiedSDJwt(vpToken);
            X509Certificate cert = openID4VPResponseService.certificate(unverifiedSDJwt);
            JWSVerifier jwsVerifier = openID4VPResponseService.jwsVerifier(cert);
            JWSAlgorithm jwsAlgorithm = openID4VPResponseService.algorithm(cert);
            SimpleJWTCryptoProvider cryptoProvider = new SimpleJWTCryptoProvider(jwsAlgorithm, null, jwsVerifier);
            return openID4VPResponseService.verificationResult(cryptoProvider, unverifiedSDJwt);
        }

        StatusSdJwt statusHelperMethod(VerificationResult<id.walt.sdjwt.SDJwt> verificationResult) throws Exception {
            return openID4VPResponseService.extractStatuslistUriAndIdx(verificationResult);
        }

    }
}